import os
import requests
from urllib.parse import urljoin, unquote

base_url = "https://z3rsim.com/"
asset_paths = [
    '/assets/dungeon-tracker-icons/chest13.png',
   '/assets/maps/Dark World/dw-hint-cave.png',
   '/assets/maps/Light World/lw-hint-cave.png',
    "/assets/dungeon-tracker-icons/dungeon1.png",

]
#asset_paths = [
    # 'assets/maps/Dark World/dw-hammer-pegs.png', 
    # 'assets/maps/Dark World/dw-hype-cave.png', 
    # 'assets/maps/Dark World/dw-bomb-shop.png', 
    # 'assets/maps/Dark World/dw-ganon.png', 
    # 'assets/maps/Dark World/dw-fat-fairy.png', 
    # 'assets/maps/Dark World/dw-mire-shed.png',
    # 'assets/maps/Misery Mire/mm-compass-flipped.png', 
    # 'assets/maps/Misery Mire/mm-map-flipped.png',
    # 'assets/maps/Misery Mire/mm-fish-spine.png',
    # 'assets/maps/Misery Mire/mm-fish-spine-flipped.png', 
    # 'assets/maps/Dark World/dw-tr-ledge.png',
    # 'assets/maps/Light World/lw-tr-ledge.png',
    # 'assets/maps/Light World/lw-mimic.png', 
    # 'assets/maps/undefined/Ganon.png'

# "assets/maps/Light World/lw-sq.png"
# "assets/maps/Light World/lw-flute-map.png"
    # "assets/maps/Light World/lw-small-shop.png",
    # "assets/maps/Light World/lw-eastern-palace.png",
    # "assets/maps/Dark World/dw-octorok-field.png",
    # "assets/maps/Dark World/dw-eastern-palace.png",
    # "assets/maps/Light World/lw-saha.png",
    # "assets/maps/Dark World/dw-flute5.png",
    # "assets/maps/Light World/lw-zora-entrance.png",
    # "assets/maps/Light World/lw-waterfall.png",
    # "assets/maps/Light World/lw-zora-domain.png",
    # "assets/maps/Dark World/dw-zora-entrance.png",
    # "assets/maps/Dark World/dw-lake-hylea.png",
    # "assets/maps/Light World/lw-hobo-entrance.png",
    # "assets/maps/Dark World/dw-small-shop.png",
    # "assets/maps/Dark World/dw-kak-portal.png",
    # "assets/maps/Dark World/dw-bombable-hut.png",
    # "assets/maps/Dark World/dw-chouse.png",
    # "assets/maps/Dark World/dw-chest-game.png",
    # "assets/maps/Light World/lw-hobo.png",
    # "assets/maps/Dark World/dw-hobo-entrance.png"
#  "assets/maps/Light World/lw-flute4.png",
#     "assets/maps/Light World/lw-octorok-field.png",
#     "assets/maps/Light World/lw-hyrule-castle.png",
#     "assets/maps/Light World/lw-south-house-portal.png",
#     "assets/maps/Light World/lw-minimoldorm-entrance.png",
#     "assets/maps/Light World/lw-flute7.png",
#     "assets/maps/Light World/lw-east-sanctuary.png",
#     "assets/maps/Light World/lw-sanctuary-entrance.png",
#     "assets/maps/Hyrule Castle/hc-boomerang.png",
#     "assets/maps/Hyrule Castle/hc-zelda.png",
#     "assets/maps/Light World/lw-flute8.png",
#     "assets/maps/Dark World/dw-lumberjack.png",
#     "assets/maps/Light World/lw-lumberjack-item.png",
#     "assets/maps/Light World/lw-pedestal.png",
#     "assets/maps/Dark World/dw-lostwoods.png",
#     "assets/maps/Light World/lw-thief-hideout.png",
#     "assets/maps/Dark World/dw-grove.png",
#     "assets/maps/Light World/lw-lake-hylea.png",
#     "assets/maps/Dark World/dw-minimoldorm-entrance.png",
#     "assets/maps/Light World/lw-minimoldorm.png",
#     "assets/maps/Light World/lw-icerod.png",
#     "assets/maps/Dark World/dw-flute8.png",
#     "assets/maps/Hyrule Castle/hc-bombablewall.png",
#     "assets/maps/Light World/lw-kingstomb.png",
#     "assets/maps/Dark World/dw-graveyard.png",
#     "assets/maps/Light World/lw-gy-ledge.png",
#     "assets/maps/Light World/lw-flute5.png",
#     "assets/maps/Light World/lw-spectacle-rock.png",
#     "assets/maps/Light World/lw-east.png",
#     "assets/maps/Dark World/dw-flute1.png",
#     "assets/maps/Light World/lw-paradox2.png",
#     "assets/maps/Light World/lw-paradox5.png",
#     "assets/maps/Dark World/dw-east.png",
#     "assets/maps/Light World/lw-trportal.png",
#     "assets/maps/Light World/lw-hera.png",
#     "assets/maps/Light World/lw-spiral.png",
#     "assets/maps/Dark World/dw-trportal.png",
#     "assets/maps/Dark World/dw-superbunny.png",
#     "assets/maps/Dark World/dw-hookshotcave.png",
#     "assets/maps/Dark World/dw-hera.png",
#     "assets/maps/Dark World/dw-spectacle-rock.png",
#     "assets/maps/Dark World/dw-spikecave.png",
#     "assets/maps/Light World/lw-spectacle-cave.png"
# "/assets/item-icons/flute.png",
# "/assets/item-icons/map.png",
# "/assets/item-icons/pendantCourage.png",
# "/assets/item-icons/redCrystal.png",
# "/assets/item-icons/mirror.png",
# "/assets/item-icons/compass.png",
# "/assets/item-icons/compassEmpty.png",
# "/assets/item-icons/bigKey.png",
# "/assets/item-icons/bigKeyEmpty.png",
# "/assets/item-icons/mapEmpty.png",
# "/assets/node-icons/big_door.png",
# "/assets/node-icons/closed_big_chest.png",
# "/assets/node-icons/closed_chest.png",
# "/assets/node-icons/key_door.png",
# "/assets/node-icons/open_chest.png",
# "/assets/node-icons/open_big_chest.png",
# "/assets/node-icons/small_key.png",
# "/assets/node-icons/warp.png",
# "/assets/node-icons/open_door.png",
# "/assets/dungeon-tracker-icons/boss92.png",
# "/assets/dungeon-tracker-icons/boss.png",
# "/assets/dungeon-tracker-icons/boss102.png",
# "/assets/dungeon-tracker-icons/boss82.png",
# "/assets/dungeon-tracker-icons/medallion0.png",
# "/assets/light-world.png",
# "/assets/dark-world.png",
# "/assets/maps/Ice Palace/ip-switch-room-block.png",
# # "/assets/maps/{dungeon}/{map}.png",
# # "/assets/maps/{dungeon}/{map}-flooded.png",
# # "/assets/maps/{dungeon}/{map}-flooded-flipped.png",
# # "/assets/maps/{dungeon}/{map}-flipped.png",
# # "/assets/maps/{dungeon}/{map}.png",
# "/assets/item-icons/hintTile.png",
# "/assets/item-icons/sign.png",
# "/assets/node-icons/blind.png",
# "/assets/node-icons/switch_blue.png",
# "/assets/node-icons/switch_red.png",
# "/assets/node-icons/water_switch_off.png",
# "/assets/node-icons/water_switch_on.png",
# "/assets/node-icons/tt_floor_closed.png",
# "/assets/node-icons/tt_floor_open.png",
# "/assets/node-icons/push-block.png",
# "/assets/node-icons/empty.png",
# "/assets/node-icons/frog.png",
# "/assets/node-icons/purple-chest.png",
# "/assets/node-icons/big-bomb.png",
# "/assets/node-icons/tablet.png",
# "/assets/node-icons/pedestal.png",
# "/assets/node-icons/hint_tile.png",
# "/assets/item-icons/hintTile.png",
# "/assets/item-icons/sign.png",
# "/assets/node-icons/duck.png",
# "/assets/node-icons/hole.png",
# "/assets/node-icons/water-warp.png",
# "/assets/node-icons/links_house.png",
#     "/assets/node-icons/sanctuary.png",
#     "/assets/node-icons/mountain_cave.png",
#     "/assets/item-icons/sword1.png",
#     "/assets/item-icons/20rupees.png",
#     "/assets/item-icons/3bombs.png",
#     "/assets/item-icons/pieceHeart.png",
#     "/assets/item-icons/glove1.png",
#     "/assets/item-icons/5rupees.png",
#     "/assets/maps/Palace%20of%20Darkness/pod-entry.png",
#     "/assets/maps/Tower%20of%20Hera/toh-entry.png",
#     "/assets/maps/Eastern%20Palace/ep-entry.png",
#     "/assets/maps/Desert%20Palace/dp-entry.png",
#     "/assets/maps/Swamp%20Palace/sp-entry.png",
#     "/assets/maps/Aga%20Tower/ct-entry.png",
#     "/assets/maps/Skull%20Woods/sw-entry.png",
#     "/assets/maps/Misery%20Mire/mm-entry.png",
#     "/assets/maps/Thieves%20Town/tt-entry.png",
#     "/assets/maps/Ice%20Palace/ip-entry.png",
#     "/assets/maps/Turtle%20Rock/tr-entry.png",
#     "/assets/maps/Ganons%20Tower/gt-entry.png",
#     "/assets/item-icons/smallKey.png",
#     "/assets/item-icons/glove2.png",
#     "/assets/item-icons/10arrows.png",
#     "/assets/item-icons/50rupees.png",
#     "/assets/item-icons/bottle1.png",
#     "/assets/item-icons/heartContainer.png",
#     "/assets/item-icons/boomerang2.png",
#     "/assets/item-icons/halfMagic1.png",
#     "/assets/item-icons/300rupees.png",
#     "/assets/item-icons/1rupee.png",
#     "/assets/item-icons/sword2.png",
#     "/assets/item-icons/shield1.png",
#     "/assets/item-icons/bottle2.png",
#     "/assets/dungeon-tracker-icons/boss112.png",
#     "/assets/item-icons/tunic2.png",
#     "/assets/item-icons/10bombs.png",
#     "/assets/item-icons/shield2.png",
#     "/assets/item-icons/shovel.png",
#     "/assets/item-icons/bow1.png",
#     "/assets/item-icons/tunic3.png",
#     "/assets/dungeon-tracker-icons/dungeon4.png",
#     "/assets/dungeon-tracker-icons/dungeonC.png",
#     "/assets/maps/Thieves%20Town/tt-stalfo-corridor.png",
#     "/assets/maps/Thieves%20Town/tt-hellway.png",
#     "/assets/maps/Thieves%20Town/tt-blind.png",
#     "/assets/maps/Thieves%20Town/tt-fork.png",
#     "/assets/maps/Thieves%20Town/tt-tile.png",
#     "/assets/maps/Thieves%20Town/tt-bombable-floor.png",
#     "/assets/maps/Thieves%20Town/tt-fork2.png",
#     "/assets/maps/Thieves%20Town/tt-maiden.png",
#     "/assets/maps/Thieves%20Town/tt-bc.png",
#     "/assets/item-icons/blind.png",
#     "/assets/item-icons/tt-bomb.png",
#     "/assets/maps/Skull%20Woods/sw-left-drop.png",
#     "/assets/maps/Skull%20Woods/sw-right-drop.png",
#     "/assets/maps/Skull%20Woods/sw-northeast-bc.png",
#     "/assets/maps/Skull%20Woods/sw-bc.png",
#     "/assets/maps/Skull%20Woods/sw-part21.png",
#     "/assets/maps/Skull%20Woods/sw-map.png",
#     "/assets/maps/Skull%20Woods/sw-gibdo-stalfo.png",
#     "/assets/maps/Skull%20Woods/sw-part22.png",
#     "/assets/maps/Skull%20Woods/sw-final.png",
#     "/assets/maps/Skull%20Woods/sw-mothula.png",
#     "/assets/item-icons/cant-item.png",
#     "/assets/maps/Swamp%20Palace/sp-tall-room.png",
#     "/assets/maps/Swamp%20Palace/sp-main-hub.png",
#     "/assets/maps/Swamp%20Palace/sp-south-switch.png",
#     "/assets/maps/Swamp%20Palace/sp-downstairs1.png",
#     "/assets/maps/Swamp%20Palace/sp-south.png",
#     "/assets/maps/Swamp%20Palace/sp-switch.png",
#     "/assets/maps/Swamp%20Palace/sp-left.png",
#     "/assets/maps/Swamp%20Palace/sp-left-key.png",
#     "/assets/maps/Swamp%20Palace/sp-south-switch-flipped.png",
#     "/assets/maps/Swamp%20Palace/sp-south-switch-flooded.png",
#     "/assets/maps/Swamp%20Palace/sp-south-switch-flooded-flipped.png",
#     "/assets/maps/Swamp%20Palace/sp-switch-flipped.png",
#     "/assets/maps/Swamp%20Palace/sp-switch-flooded.png",
#     "/assets/maps/Swamp%20Palace/sp-switch-flooded-flipped.png",
#     "/assets/item-icons/switch.png",
#     "/assets/item-icons/flood.png",
#     "/assets/maps/Swamp%20Palace/sp-left-flipped.png",
#     "/assets/maps/Swamp%20Palace/sp-downstairs2.png",
#     "/assets/maps/Swamp%20Palace/sp-arrghus.png",
#     "/assets/item-icons/crystal.png",
#     "/assets/item-icons/bow2.png",
#     "/assets/maps/Ice%20Palace/ip-first-fork.png",
#     "/assets/maps/Ice%20Palace/ip-compass.png",
#     "/assets/maps/Ice%20Palace/ip-tile.png",
#     "/assets/maps/Ice%20Palace/ip-conveyor-room.png",
#     "/assets/maps/Ice%20Palace/ip-bj.png",
#     "/assets/maps/Ice%20Palace/ip-plus.png",
#     "/assets/maps/Ice%20Palace/ip-bj-flipped.png",
#     "/assets/maps/Ice%20Palace/ip-spike-room.png",
#     "/assets/maps/Ice%20Palace/ip-tall-room.png",
#     "/assets/maps/Ice%20Palace/ip-double-freezor.png",
#     "/assets/maps/Ice%20Palace/ip-bc.png",
#     "/assets/maps/Ice%20Palace/ip-double-jelly.png",
#     "/assets/maps/Ice%20Palace/ip-map.png",
#     "/assets/maps/Ice%20Palace/ip-bk.png",
#     "/assets/maps/Ice%20Palace/ip-push-block.png",
#     "/assets/maps/Ice%20Palace/ip-icy-pot.png",
#     "/assets/maps/Ice%20Palace/ip-fairy-drop.png",
#     "/assets/maps/Ice%20Palace/ip-push-block-flipped.png",
#     "/assets/maps/Ice%20Palace/ip-pre-khold.png",
#     "/assets/maps/Ice%20Palace/ip-final-switch.png",
#     "/assets/item-icons/ip-switch-room.png",
#     "/assets/maps/Ice%20Palace/ip-switch-room.png",
#     "/assets/maps/Ice%20Palace/ip-khold.png",
#     "/assets/maps/Desert%20Palace/dp-torch.png",
#     "/assets/maps/Desert%20Palace/dp-bc.png",
#     "/assets/maps/Desert%20Palace/dp-right.png",
#     "/assets/maps/Desert%20Palace/dp-map.png",
#     "/assets/maps/Desert%20Palace/dp-first-tile.png",
#     "/assets/maps/Desert%20Palace/dp-big-door.png",
#     "/assets/maps/Desert%20Palace/dp-lanmo.png",
#     "/assets/item-icons/sword3.png",
#     "/assets/maps/Tower%20of%20Hera/toh-upstairs.png",
#     "/assets/maps/Tower%20of%20Hera/toh-sk.png",
#     "/assets/maps/Tower%20of%20Hera/toh-basement.png",
#     "/assets/maps/Tower%20of%20Hera/toh-moldorm.png",
#     "/assets/maps/Eastern%20Palace/ep-fork.png",
#     "/assets/maps/Eastern%20Palace/ep-map.png",
#     "/assets/maps/Eastern%20Palace/ep-compass.png",
#     "/assets/maps/Eastern%20Palace/ep-tile.png",
#     "/assets/maps/Eastern%20Palace/ep-bc.png",
#     "/assets/maps/Eastern%20Palace/ep-armos.png",
#     "/assets/maps/Eastern%20Palace/ep-bk.png",
#     "/assets/item-icons/shield3.png",
#     "/assets/maps/Turtle%20Rock/tr-hall.png",
#     "/assets/maps/Turtle%20Rock/tr-compass.png",
#     "/assets/maps/Turtle%20Rock/tr-map.png",
#     "/assets/maps/Turtle%20Rock/tr-chain-chomp.png",
#     "/assets/maps/Turtle%20Rock/tr-pipe-room.png",
#     "/assets/maps/Turtle%20Rock/tr-double-pokey.png",
#     "/assets/maps/Turtle%20Rock/tr-pokey-key.png",
#     "/assets/maps/Turtle%20Rock/tr-bk.png",
#     "/assets/maps/Turtle%20Rock/tr-big-door.png",
#     "/assets/maps/Turtle%20Rock/tr-outside.png",
#     "/assets/maps/Turtle%20Rock/tr-roller-switch.png",
#     "/assets/maps/Turtle%20Rock/tr-helma-bridge.png",
#     "/assets/maps/Turtle%20Rock/tr-mimic.png",
#     "/assets/maps/Turtle%20Rock/tr-laser-bridge.png",
#     "/assets/maps/Turtle%20Rock/tr-before-tri.png",
#     "/assets/maps/Turtle%20Rock/tr-trinexx.png",
#     "/assets/item-icons/pendantPower.png",
#     "/assets/maps/Palace%20of%20Darkness/pod-left.png",
#     "/assets/maps/Palace%20of%20Darkness/pod-fork1.png",
#     "/assets/maps/Palace%20of%20Darkness/pod-tile.png",
#     "/assets/maps/Palace%20of%20Darkness/pod-right.png",
#     "/assets/maps/Palace%20of%20Darkness/pod-jump.png",
#     "/assets/maps/Palace%20of%20Darkness/pod-stalfos-drop.png",
#     "/assets/maps/Palace%20of%20Darkness/pod-bk.png",
#     "/assets/maps/Palace%20of%20Darkness/pod-statue.png",
#     "/assets/maps/Palace%20of%20Darkness/pod-to-helma.png",
#     "/assets/maps/Palace%20of%20Darkness/pod-helma.png",
#     "/assets/maps/Palace%20of%20Darkness/pod-fork2.png",
#     "/assets/maps/Palace%20of%20Darkness/pod-compass.png",
#     "/assets/maps/Palace%20of%20Darkness/pod-maze.png",
#     "/assets/item-icons/boomerang3.png",
#     "/assets/item-icons/boomerang1.png",
#     "/assets/maps/Palace%20of%20Darkness/pod-spike-statue.png",
#     "/assets/maps/Palace%20of%20Darkness/pod-basement.png",
#     "/assets/item-icons/pendantWisdom.png",
#     "/assets/item-icons/bottle3.png",
#     "/assets/maps/Misery%20Mire/mm-switch-room.png",
#     "/assets/maps/Misery%20Mire/mm-lone-stalfo.png",
#     "/assets/maps/Misery%20Mire/mm-west-spike.png",
#     "/assets/maps/Misery%20Mire/mm-map.png",
#     "/assets/maps/Misery%20Mire/mm-bc.png",
#     "/assets/maps/Misery%20Mire/mm-entry-flipped.png",
#     "/assets/maps/Misery%20Mire/mm-big-door.png",
#     "/assets/maps/Misery%20Mire/mm-two-bridges.png",
#     "/assets/maps/Misery%20Mire/mm-spike-room.png",
#     "/assets/maps/Misery%20Mire/mm-north-spike.png",
#     "/assets/maps/Misery%20Mire/mm-pre-vitty.png",
#     "/assets/maps/Misery%20Mire/mm-vitty.png",
#     "/assets/maps/Misery%20Mire/mm-four-torch.png",
#     "/assets/maps/Misery%20Mire/mm-compass.png",
#     "/assets/maps/Misery%20Mire/mm-tile.png",
#     "/assets/maps/Misery%20Mire/mm-bk.png",
#     "/assets/maps/Ganons%20Tower/gt-first-left.png",
#     "/assets/maps/Ganons%20Tower/gt-first-right.png",
#     "/assets/maps/Ganons%20Tower/gt-lanmo2.png",
#     "/assets/maps/Ganons%20Tower/gt-hammer-pegs.png",
#     "/assets/maps/Ganons%20Tower/gt-hookshot-room.png",
#     "/assets/maps/Ganons%20Tower/gt-stalfo.png",
#     "/assets/maps/Ganons%20Tower/gt-double-firebar.png",
#     "/assets/maps/Ganons%20Tower/gt-double-switch.png",
#     "/assets/item-icons/sword4.png",
#     "/assets/maps/Ganons%20Tower/gt-firesnake.png",
#     "/assets/maps/Ganons%20Tower/gt-teleports.png",
#     "/assets/maps/Ganons%20Tower/gt-rando-room.png",
#     "/assets/maps/Ganons%20Tower/gt-invisible-maze.png",
#     "/assets/maps/Ganons%20Tower/gt-bc.png",
#     "/assets/maps/Ganons%20Tower/gt-bobs-room.png",
#     "/assets/maps/Ganons%20Tower/gt-armos.png",
#     "/assets/maps/Ganons%20Tower/gt-bk.png",
#     "/assets/maps/Ganons%20Tower/gt-tile-room.png",
#     "/assets/maps/Ganons%20Tower/gt-right-side.png",
#     "/assets/maps/Ganons%20Tower/gt-sk-corridor.png",
#     "/assets/item-icons/singleArrow.png",
#     "/assets/item-icons/100rupees.png",
#     "/assets/maps/Ganons%20Tower/gt-upstairs.png",
#     "/assets/maps/Ganons%20Tower/gt-refill.png",
#     "/assets/maps/Ganons%20Tower/gt-moldorm.png",
#     "/assets/item-icons/bottle4.png",
#     "/assets/maps/Ganons%20Tower/gt-aga2.png",
#     "/assets/item-icons/agahnim1.png",
#     "/assets/item-icons/Ganon.png",
#     "/assets/maps/Ice%20Palace/ip-final-switch-flipped.png",
#     "/assets/maps/Turtle%20Rock/tr-bc.png",
#     "/assets/maps/Aga%20Tower/ct-maze.png",
#     "/assets/maps/Aga%20Tower/ct-tile.png",
#     "/assets/maps/Aga%20Tower/ct-top.png",
#     "/assets/maps/Aga%20Tower/ct-aga.png",
#     "/assets/maps/Light%20World/lw-flute1.png",
#     "/assets/maps/Light%20World/lw-linkshouse.png",
#     "/assets/maps/Hyrule%20Castle/hc-sanctuary.png",
#     "/assets/maps/Light%20World/lw-south-grove.png",
#     "/assets/maps/Dark%20World/dw-flute4.png",
#     "/assets/maps/Light%20World/lw-graveyard.png",
#     "/assets/maps/Dark%20World/dw-east-sanctuary.png",
#     "/assets/maps/Light%20World/lw-flute2.png",
#     "/assets/maps/Light%20World/lw-potion-shop.png",
#     "/assets/maps/Dark%20World/dw-flute2.png",
#     "/assets/maps/Light%20World/lw-uncle.png",
#     "/assets/maps/Hyrule%20Castle/hc-left.png",
#     "/assets/maps/Hyrule%20Castle/hc-entry.png",
#     "/assets/maps/Dark%20World/dw-hyrule-castle.png",
#     "/assets/maps/Hyrule%20Castle/hc-darkchest.png",
#     "/assets/maps/Hyrule%20Castle/hc-keyrat.png",
#     "/assets/maps/Hyrule%20Castle/hc-map.png",
#     "/assets/maps/Light%20World/lw-fortune-teller.png",
#     "/assets/maps/Light%20World/lw-lumberjack.png",
#     "/assets/maps/Light%20World/lw-bonkrocks.png",
#     "/assets/maps/Dark%20World/dw-sanctuary-entrance.png",
#     "/assets/maps/Light%20World/lw-kakariko.png",
#     "/assets/maps/Light%20World/lw-lostwoods.png",
#     "/assets/maps/Dark%20World/dw-fortune-teller.png",
#     "/assets/maps/Light%20World/lw-blacksmiths-entrance.png",
#     "/assets/maps/Light%20World/lw-kak-portal.png",
#     "/assets/maps/Light%20World/lw-well.png",
#     "/assets/maps/Light%20World/lw-race-game.png",
#     "/assets/maps/Light%20World/lw-blindshut.png",
#     "/assets/maps/Light%20World/lw-chicken.png",
#     "/assets/maps/Dark%20World/dw-kakariko.png",
#     "/assets/maps/Light%20World/lw-sickkid.png",
#     "/assets/maps/Light%20World/lw-bar.png",
#     "/assets/maps/Light%20World/lw-bat.png",
#     "/assets/maps/Light%20World/lw-blacksmiths.png",
#     "/assets/maps/Dark%20World/dw-blacksmiths-entrance.png",
#     "/assets/maps/Light%20World/lw-library.png",
#     "/assets/maps/Light%20World/lw-grove.png",
#     "/assets/maps/Light%20World/lw-south-grove-cave.png",
#     "/assets/maps/Dark%20World/dw-south-grove.png",
#     "/assets/maps/Dark%20World/dw-south-house-portal.png",
#     "/assets/maps/Light%20World/lw-desert.png",
#     "/assets/maps/Dark%20World/dw-flute7.png",
#     "/assets/maps/Light%20World/lw-dam.png",
#     "/assets/maps/Light%20World/lw-aginah.png",
#     "/assets/maps/Light%20World/lw-checkerboard.png",
#     "/assets/maps/Dark%20World/dw-desert.png",
#     "/assets/maps/Dark%20World/dw-race-game.png",
#     "/assets/maps/Hyrule%20Castle/hc-left.png",
#     "/assets/maps/Hyrule%20Castle/hc-entry.png",
#     "/assets/maps/Hyrule%20Castle/hc-darkchest.png",
#     "/assets/maps/Hyrule%20Castle/hc-keyrat.png",
#     "/assets/maps/Hyrule%20Castle/hc-map.png"
# ]

# Filter out paths with placeholders
asset_paths = [path for path in asset_paths if "{" not in path]

for path in asset_paths:
    # Construct the full URL
    url = urljoin(base_url, path.strip())
    
    # Determine the local file path
    # Remove the leading slash from the path for os.path.join
    # Convert URL-encoded characters (%20) to spaces
    local_path = os.path.join(os.getcwd(), unquote(path.lstrip('/')))
    
    # Create the directory if it doesn't exist
    os.makedirs(os.path.dirname(local_path), exist_ok=True)
    
    # Download the file
    try:
        response = requests.get(url, stream=True)
        response.raise_for_status()  # Raise an exception for bad status codes
        with open(local_path, 'wb') as f:
            for chunk in response.iter_content(chunk_size=8192):
                f.write(chunk)
        print(f"Successfully downloaded {url} to {local_path}")
    except requests.exceptions.RequestException as e:
        print(f"Failed to download {url}. Error: {e}")

print("Asset download script finished.")
